version: "3"
services:
  node:
    image: node:8-alpine
    working_dir: /usr/src/app
    env_file: .env
    volumes:
      - ./:/usr/src/app
    command: npm run start
  mongo:
    container_name: mongodb
    image: mongo